version: "3.9"

services:
  client:
    image: plclone/place-client
    build: ./place-client
    tty: true
    stdin_open: true
    working_dir: /app
    ports:
      - 9898:80
    volumes:
      - ./place-client:/app
    depends_on:
      - api
      - websocket
  api:
    image: plclone/place-api
    build: ./api
    tty: true
    stdin_open: true
    working_dir: /app
    environment:
      - PORT=8787
      - CANVAS_NAME=dev
      - CANVAS_WIDTH=2000
      - CANVAS_HEIGHT=2000
      - AVAIABLE_COLORS=0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,255
      - CASSANDRA_CONTACT_POINTS=cassandra
      - CASSANDRA_KEYSPACE=place
      - RABBIT_HOST=rabbitmq
      - RABBIT_EXCHANGE=place
      - COOLDOWN_SECONDS=300
      - REDIS_URL=redis://redis:6379
    ports:
      - 8787:8787
    volumes:
      - ./api:/app
    depends_on:
      - redis
      - cassandra
      - rabbitmq
  websocket:
    image: plclone/place-websocket
    build: ./websocket
    tty: true
    stdin_open: true
    working_dir: /app
    environment:
      - PORT=7676
      - RABBIT_HOST=rabbitmq
      - RABBIT_EXCHANGE=place
    ports:
      - 7676:7676
    volumes:
      - ./websocket:/app
    depends_on:
      - rabbitmq
    restart: on-failure
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  cassandra:
    image: cassandra
    ports:
      - 9042:9042
  cassandra-setup:
    image: cassandra
    depends_on:
      - cassandra
    restart: "no"
    entrypoint: ["/cassandra_setup.sh"]
    volumes:
      - ./scripts/cassandra_setup.sh:/cassandra_setup.sh
  rabbitmq:
    image: rabbitmq:management-alpine