version: "3.9"

services:
  client:
    env_file: .env
    image: plclone/place-api
    build: .
    tty: true
    stdin_open: true
    working_dir: /app
    ports:
      - 8787:8787
    volumes:
      - .:/app